// File Path: /server/index.js
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const authRoutes = require('./routes/auth');
const gameRoutes = require('./routes/game');
const tutorRoutes = require('./routes/tutor');
const Puzzle = require('./models/Puzzle');
require('dotenv').config();

const app = express();

// CORS configuration for multiple origins
const allowedOrigins = [
  'https://algebra-adventure.vercel.app',
  'http://localhost:5173', // For local development with Vite
];

app.use(cors({
  origin: (origin, callback) => {
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new Error('Not allowed by CORS'));
    }
  },
  credentials: true,
}));
app.use(express.json());

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'OK', message: 'Server is running for STEMZap with dynamic puzzles!' });
});

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/game', gameRoutes);
app.use('/api/tutor', tutorRoutes);

// Seed puzzles if collection is empty or outdated
const seedPuzzles = async () => {
  try {
    const puzzleCount = await Puzzle.countDocuments();
    console.log(`Current puzzle count: ${puzzleCount}`);
    if (puzzleCount < 75) { // Ensure at least 75 puzzles
      console.log('Seeding initial puzzles...');
      await Puzzle.deleteMany({}); // Clear existing puzzles to avoid duplicates
      const initialPuzzles = [
        // Linear Equations (25 puzzles)
        {
          type: 'linear',
          question: 'Solve for x: 2x + 3 = 7',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 3 from both sides to isolate the term with x.',
          isDailyChallenge: true,
        },
        {
          type: 'linear',
          question: 'Solve for x: x + 2 = 5',
          answer: '3',
          curriculum: 'Common Core',
          standard: '6.EE.B.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'What number plus 2 equals 5? Subtract 2 from both sides.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 3x^2 + 2x - 5 = 0',
          answer: '1, -5/3',
          curriculum: 'Common Core',
          standard: 'A-REI.B.4',
          topic: 'Quadratic Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['engineering'],
          hint: 'Use the quadratic formula: x = [-b ± √(b² - 4ac)] / (2a).',
        },
        {
          type: 'linear',
          question: 'Solve for x: 4x - 8 = 0',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 8 to both sides, then divide by 4.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 5x + 10 = 20',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 10 from both sides, then divide by 5.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 7x - 14 = 0',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 14 to both sides, then divide by 7.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 3x + 9 = 18',
          answer: '3',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 9 from both sides, then divide by 3.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 2x - 4 = 6',
          answer: '5',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Add 4 to both sides, then divide by 2.',
        },
        {
          type: 'linear',
          question: 'Solve for x: x/2 + 3 = 5',
          answer: '4',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 3 from both sides, then multiply by 2.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 5x^2 - 10x + 5 = 0',
          answer: '1',
          curriculum: 'Common Core',
          standard: 'A-REI.B.4',
          topic: 'Quadratic Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['engineering'],
          hint: 'Factor the equation: 5(x - 1)^2 = 0.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 6x + 12 = 24',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 12 from both sides, then divide by 6.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 8x - 16 = 0',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 16 to both sides, then divide by 8.',
        },
        {
          type: 'linear',
          question: 'Solve for x: x - 3 = 7',
          answer: '10',
          curriculum: 'Common Core',
          standard: '6.EE.B.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Add 3 to both sides.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 4x + 5 = 17',
          answer: '3',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 5 from both sides, then divide by 4.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 2x + 1 = 9',
          answer: '4',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 1 from both sides, then divide by 2.',
        },
        {
          type: 'linear',
          question: 'Solve for x: x/3 - 2 = 1',
          answer: '9',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 2 to both sides, then multiply by 3.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 9x - 18 = 0',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 18 to both sides, then divide by 9.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 3x - 6 = 9',
          answer: '5',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Add 6 to both sides, then divide by 3.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 2x^2 - 8 = 0',
          answer: '2, -2',
          curriculum: 'Common Core',
          standard: 'A-REI.B.4',
          topic: 'Quadratic Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['engineering'],
          hint: 'Add 8 to both sides, then take the square root of both sides.',
          isDailyChallenge: true,
        },
        {
          type: 'linear',
          question: 'Solve for x: 5x + 15 = 30',
          answer: '3',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 15 from both sides, then divide by 5.',
        },
        {
          type: 'linear',
          question: 'Solve for x: x + 7 = 12',
          answer: '5',
          curriculum: 'Common Core',
          standard: '6.EE.B.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Subtract 7 from both sides.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 6x - 12 = 6',
          answer: '3',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Add 12 to both sides, then divide by 6.',
        },
        {
          type: 'linear',
          question: 'Solve for x: x/4 + 1 = 3',
          answer: '8',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 1 from both sides, then multiply by 4.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 4x^2 - 16 = 0',
          answer: '2, -2',
          curriculum: 'Common Core',
          standard: 'A-REI.B.4',
          topic: 'Quadratic Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['engineering'],
          hint: 'Add 16 to both sides, divide by 4, then take the square root.',
        },
        {
          type: 'linear',
          question: 'Solve for x: 10x + 20 = 40',
          answer: '2',
          curriculum: 'Common Core',
          standard: '8.EE.C.7',
          topic: 'Linear Equations',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Subtract 20 from both sides, then divide by 10.',
        },

        // Fractions (25 puzzles)
        {
          type: 'fraction',
          question: 'Simplify the fraction: 4/8',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Divide both the numerator and denominator by their greatest common divisor, 4.',
          isDailyChallenge: true,
        },
        {
          type: 'fraction',
          question: 'Add the fractions: 1/3 + 1/6',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Find a common denominator by multiplying the denominators: 3 * 6 = 18.',
        },
        {
          type: 'fraction',
          question: 'Multiply the fractions: 2/3 * 3/4',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.B.4',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply the numerators (2 * 3) and denominators (3 * 4), then simplify.',
        },
        {
          type: 'fraction',
          question: 'Subtract the fractions: 3/4 - 1/2',
          answer: '1/4',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Convert 1/2 to 2/4, then subtract the numerators.',
        },
        {
          type: 'fraction',
          question: 'Divide the fractions: 2/5 ÷ 1/3',
          answer: '6/5',
          curriculum: 'Common Core',
          standard: '5.NF.B.7',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply by the reciprocal of 1/3, which is 3/1.',
        },
        {
          type: 'fraction',
          question: 'Simplify the fraction: 6/9',
          answer: '2/3',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Divide both the numerator and denominator by 3.',
        },
        {
          type: 'fraction',
          question: 'Add the fractions: 2/5 + 3/10',
          answer: '7/10',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Convert 2/5 to 4/10, then add the numerators.',
        },
        {
          type: 'fraction',
          question: 'Multiply the fractions: 1/2 * 3/5',
          answer: '3/10',
          curriculum: 'Common Core',
          standard: '5.NF.B.4',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply the numerators (1 * 3) and denominators (2 * 5).',
        },
        {
          type: 'fraction',
          question: 'Subtract the fractions: 5/6 - 1/3',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Convert 1/3 to 2/6, then subtract the numerators.',
        },
        {
          type: 'fraction',
          question: 'Divide the fractions: 3/4 ÷ 1/2',
          answer: '3/2',
          curriculum: 'Common Core',
          standard: '5.NF.B.7',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply by the reciprocal of 1/2, which is 2/1.',
        },
        {
          type: 'fraction',
          question: 'Simplify the fraction: 8/12',
          answer: '2/3',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Divide both the numerator and denominator by 4.',
        },
        {
          type: 'fraction',
          question: 'Add the fractions: 1/4 + 1/8',
          answer: '3/8',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Convert 1/4 to 2/8, then add the numerators.',
        },
        {
          type: 'fraction',
          question: 'Multiply the fractions: 4/5 * 2/3',
          answer: '8/15',
          curriculum: 'Common Core',
          standard: '5.NF.B.4',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply the numerators (4 * 2) and denominators (5 * 3).',
        },
        {
          type: 'fraction',
          question: 'Subtract the fractions: 7/8 - 3/8',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Since the denominators are the same, subtract the numerators directly.',
        },
        {
          type: 'fraction',
          question: 'Divide the fractions: 5/6 ÷ 2/3',
          answer: '5/4',
          curriculum: 'Common Core',
          standard: '5.NF.B.7',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply by the reciprocal of 2/3, which is 3/2.',
        },
        {
          type: 'fraction',
          question: 'Simplify the fraction: 10/15',
          answer: '2/3',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Divide both the numerator and denominator by 5.',
        },
        {
          type: 'fraction',
          question: 'Add the fractions: 3/5 + 1/10',
          answer: '7/10',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Convert 3/5 to 6/10, then add the numerators.',
        },
        {
          type: 'fraction',
          question: 'Multiply the fractions: 2/7 * 3/4',
          answer: '3/14',
          curriculum: 'Common Core',
          standard: '5.NF.B.4',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply the numerators (2 * 3) and denominators (7 * 4).',
        },
        {
          type: 'fraction',
          question: 'Subtract the fractions: 2/3 - 1/6',
          answer: '1/2',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Convert 2/3 to 4/6, then subtract the numerators.',
        },
        {
          type: 'fraction',
          question: 'Divide the fractions: 4/5 ÷ 2/5',
          answer: '2',
          curriculum: 'Common Core',
          standard: '5.NF.B.7',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply by the reciprocal of 2/5, which is 5/2.',
          isDailyChallenge: true,
        },
        {
          type: 'fraction',
          question: 'Simplify the fraction: 12/18',
          answer: '2/3',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Divide both the numerator and denominator by 6.',
        },
        {
          type: 'fraction',
          question: 'Add the fractions: 1/2 + 1/4',
          answer: '3/4',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Convert 1/2 to 2/4, then add the numerators.',
        },
        {
          type: 'fraction',
          question: 'Multiply the fractions: 5/6 * 2/3',
          answer: '5/9',
          curriculum: 'Common Core',
          standard: '5.NF.B.4',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply the numerators (5 * 2) and denominators (6 * 3).',
        },
        {
          type: 'fraction',
          question: 'Subtract the fractions: 4/5 - 2/5',
          answer: '2/5',
          curriculum: 'Common Core',
          standard: '5.NF.A.1',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['primary', 'high'],
          hint: 'Since the denominators are the same, subtract the numerators directly.',
        },
        {
          type: 'fraction',
          question: 'Divide the fractions: 3/8 ÷ 1/4',
          answer: '3/2',
          curriculum: 'Common Core',
          standard: '5.NF.B.7',
          topic: 'Fractions',
          theme: 'Adventure',
          language: 'English',
          educationLevel: ['high', 'college'],
          hint: 'Multiply by the reciprocal of 1/4, which is 4/1.',
        },

        // Coding Challenges (25 puzzles)
        {
          type: 'coding',
          question: 'Write a Python function to check if a number is even.',
          answer: 'def is_even(num): return num % 2 == 0',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Use the modulo operator % to check if the number is divisible by 2.',
          isDailyChallenge: true,
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the maximum of three numbers.',
          answer: 'def max_of_three(a, b, c): return max(a, b, c)',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['college', 'engineering'],
          hint: 'Use Python’s built-in max() function to compare the numbers.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to reverse a string.',
          answer: 'function reverseString(str) { return str.split("").reverse().join(""); }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['high', 'college'],
          hint: 'Split the string into an array, reverse it, then join it back.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to sum an array of numbers.',
          answer: 'function sumArray(arr) { return arr.reduce((sum, num) => sum + num, 0); }',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['college', 'engineering'],
          hint: 'Use the reduce() method to add all numbers in the array.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to calculate factorial of a number.',
          answer: 'def factorial(n): return 1 if n == 0 else n * factorial(n-1)',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['college', 'engineering'],
          hint: 'Use recursion: factorial(n) = n * factorial(n-1), with base case 0! = 1.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to check if a string is a palindrome.',
          answer: 'def is_palindrome(s): return s == s[::-1]',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['high', 'college'],
          hint: 'Compare the string with its reverse using slicing.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to find the length of a string.',
          answer: 'function stringLength(str) { return str.length; }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['primary', 'high'],
          hint: 'Use the length property of the string.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to count vowels in a string.',
          answer: 'def count_vowels(s): return sum(1 for char in s.lower() if char in "aeiou")',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['college', 'engineering'],
          hint: 'Convert the string to lowercase and check each character against "aeiou".',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to check if a number is positive.',
          answer: 'function isPositive(num) { return num > 0; }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['primary', 'high'],
          hint: 'Return true if the number is greater than 0.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the square of a number.',
          answer: 'def square(num): return num * num',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Multiply the number by itself.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to check if a number is odd.',
          answer: 'function isOdd(num) { return num % 2 !== 0; }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['primary', 'high'],
          hint: 'Use the modulo operator to check if the number is not divisible by 2.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the minimum of two numbers.',
          answer: 'def min_of_two(a, b): return min(a, b)',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Use Python’s built-in min() function.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to capitalize the first letter of a string.',
          answer: 'function capitalize(str) { return str.charAt(0).toUpperCase() + str.slice(1); }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['high', 'college'],
          hint: 'Use charAt(0) to get the first letter, toUpperCase() to capitalize it, and slice(1) for the rest.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to check if a number is prime.',
          answer: 'def is_prime(n): if n < 2: return False; for i in range(2, int(n**0.5) + 1): if n % i == 0: return False; return True',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['college', 'engineering'],
          hint: 'Check divisibility up to the square root of the number.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to find the average of an array.',
          answer: 'function average(arr) { return arr.reduce((sum, num) => sum + num, 0) / arr.length; }',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['college', 'engineering'],
          hint: 'Sum the array using reduce(), then divide by the array length.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to reverse a list.',
          answer: 'def reverse_list(lst): return lst[::-1]',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['high', 'college'],
          hint: 'Use list slicing with [::-1] to reverse the list.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to check if a string contains a substring.',
          answer: 'function containsSubstring(str, sub) { return str.includes(sub); }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['high', 'college'],
          hint: 'Use the includes() method to check for the substring.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the sum of a list.',
          answer: 'def sum_list(lst): return sum(lst)',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Use Python’s built-in sum() function.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to remove duplicates from an array.',
          answer: 'function removeDuplicates(arr) { return [...new Set(arr)]; }',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['college', 'engineering'],
          hint: 'Use a Set to remove duplicates, then convert back to an array.',
          isDailyChallenge: true,
        },
        {
          type: 'coding',
          question: 'Write a Python function to check if a list is empty.',
          answer: 'def is_empty(lst): return len(lst) == 0',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Check if the length of the list is 0.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to find the maximum number in an array.',
          answer: 'function findMax(arr) { return Math.max(...arr); }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['high', 'college'],
          hint: 'Use Math.max() with the spread operator to find the largest number.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the length of a list.',
          answer: 'def list_length(lst): return len(lst)',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Use Python’s built-in len() function.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to check if an array is empty.',
          answer: 'function isEmpty(arr) { return arr.length === 0; }',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['primary', 'high'],
          hint: 'Check if the array’s length is 0.',
        },
        {
          type: 'coding',
          question: 'Write a Python function to find the cube of a number.',
          answer: 'def cube(num): return num ** 3',
          curriculum: 'CSTA',
          standard: '2-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'python',
          educationLevel: ['primary', 'high'],
          hint: 'Use the ** operator to raise the number to the power of 3.',
        },
        {
          type: 'coding',
          question: 'Write a JavaScript function to count occurrences of a character in a string.',
          answer: 'function countChar(str, char) { return str.split(char).length - 1; }',
          curriculum: 'CSTA',
          standard: '3A-AP-13',
          topic: 'Programming',
          theme: 'Adventure',
          language: 'javascript',
          educationLevel: ['college', 'engineering'],
          hint: 'Split the string by the character and count the resulting segments.',
        },
      ];
      await Puzzle.insertMany(initialPuzzles);
      console.log(`Seeded ${initialPuzzles.length} puzzles successfully`);
    } else {
      console.log('Puzzle collection already populated');
    }
  } catch (err) {
    console.error('Error seeding puzzles:', err.message, err.stack);
  }
};

const startServer = async () => {
  try {
    if (!process.env.MONGODB_URI) {
      throw new Error('MONGODB_URI is not defined in .env');
    }
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('Connected to MongoDB');

    // Seed puzzles after connecting
    await seedPuzzles();

    const port = process.env.PORT || 5000;
    app.listen(port, () => {
      console.log(`Server running on port ${port}`);
    });
  } catch (err) {
    console.error('Failed to start server:', err.message, err.stack);
    process.exit(1);
  }
};

startServer();

process.on('uncaughtException', (err) => {
  console.error('Uncaught Exception:', err.message, err.stack);
  process.exit(1);
});

process.on('unhandledRejection', (err) => {
  console.error('Unhandled Rejection:', err.message, err.stack);
  process.exit(1);
});